from pymeos_cffi import *
from ..boxes import TBox as TBox
from ..main import TFloat as TFloat, TInt as TInt, TNumber as TNumber
from .aggregator import BaseAggregator as BaseAggregator

class TemporalAverageAggregator(BaseAggregator[TNumber, TNumber]): ...
class TemporalNumberExtentAggregator(BaseAggregator[TNumber, TBox]): ...
class TemporalIntMaxAggregator(BaseAggregator[TInt, TInt]): ...
class TemporalIntMinAggregator(BaseAggregator[TInt, TInt]): ...
class TemporalIntSumAggregator(BaseAggregator[TInt, TInt]): ...
class TemporalFloatMaxAggregator(BaseAggregator[TFloat, TFloat]): ...
class TemporalFloatMinAggregator(BaseAggregator[TFloat, TFloat]): ...
class TemporalFloatSumAggregator(BaseAggregator[TFloat, TFloat]): ...
