from pymeos_cffi import *
from ..base import Set as Set
from typing import overload

class TextSet(Set[str]):
    def to_spanset(self) -> None: ...
    def to_span(self) -> None: ...
    def start_element(self): ...
    def end_element(self): ...
    def element_n(self, n: int): ...
    def elements(self): ...
    def contains(self, content: TextSet | str) -> bool: ...
    def lowercase(self): ...
    def uppercase(self): ...
    @overload
    def intersection(self, other: str) -> str | None: ...
    @overload
    def intersection(self, other: TextSet) -> TextSet | None: ...
    def minus(self, other: TextSet | str) -> TextSet | None: ...
    def subtract_from(self, other: str) -> str | None: ...
    def union(self, other: TextSet | str) -> TextSet: ...
