from ..main import TBool as TBool
from ..temporal import Temporal as Temporal
from typing import TypeVar

Self = TypeVar('Self', bound='Temporal[Any]')

class TTemporallyEquatable:
    def temporal_equal(self, other: Temporal) -> TBool: ...
    def temporal_not_equal(self, other: Temporal) -> TBool: ...

class TTemporallyComparable:
    def temporal_less(self, other: Temporal) -> TBool: ...
    def temporal_less_or_equal(self, other: Temporal) -> TBool: ...
    def temporal_greater_or_equal(self, other: Temporal) -> TBool: ...
    def temporal_greater(self, other: Temporal) -> TBool: ...
